theme: jekyll-theme-minimal
# Site
title: StudyTrack
subtitle: Учеба за рубежом
description: Возим детей и отправляем взрослых в зарубежные языковые школы
author: Konstantin Likhtin
language: "ru-RU"
date_format: '%Y-%m-%d'
